export const PUSH_USER = "PUSH_USER";
export const FORM_IS_VALID = "FORM_IS_VALID";
export const PUT_USERNAME_AND_PASSWORD = "PUT_USERNAME_AND_PASSWORD";
export const CHECK_SIGN_IN = "CHECK_SIGN_IN";
export const PUT_LOCALSTORAGE_IN_USSERS = "PUT_LOCALSTORAGE_IN_USSERS";

export const ADD_MONEY_TO_ACTIONS_ARR = "ADD_MONEY_TO_ACTIONS_ARR";
export const TAKE_OF_MONEY = "TAKE_OF_MONEY";
export const DELETE_ITEM = "DELETE_ITEM";
export const TRANSFER_MONEY_FUN = "TRANSFER_MONEY_FUN";
export const LOGOUT_FUN = "LOGOUT_FUN";
